addons:
    sonarcloud:
        organization: "adamwight-github"
language: node_js
node_js:
    - node
script:
    - npm run build
    - sonar-scanner -D sonar.login="$SONAR_TOKEN"
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
